---
- name: 'Ensure MS Teams is provisioned for package manager ({{ ansible_pkg_mgr }})'
  include_tasks: 'tasks-{{ ansible_pkg_mgr }}.yml'
  when: ansible_pkg_mgr in ('apt', 'dnf')

- fail:
    msg: ERROR This role is not setup to deal with package manager {{ ansible_pkg_mgr }}
  when: ansible_pkg_mgr not in ('apt', 'dnf')