---
- name: Ensure MS signing signing key is present
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
- name: Ensure MS Teams apt repo is present
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
    state: present
    filename: microsoft-teams
- name: Ensure MS teams package is present
  apt:
    update_cache: yes
    name: teams
    state: present